version: '3.8'
services:
  frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
    image: tlsguard-frontend:latest
    container_name: tlsguard-frontend
    ports:
      - "3000:3000"
    restart: unless-stopped

  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    image: tlsguard-backend:latest
    container_name: tlsguard-backend
    ports:
      - "4000:3000"
    environment:
      - PORT=3000
    volumes:
      - ai-backend-data:/app/backend/data
    restart: unless-stopped

  jenkins-ci:
    build:
      context: .
      dockerfile: Jenkins.Dockerfile
    image: tlsguard-jenkins:latest
    container_name: jenkins-ci
    ports:
      - "8085:8080"
    user: "root"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

volumes:
  jenkins_home:
  ai-backend-data:
